version: '3.8'

services:
  ollama:
    build:
      context: ./ollama_server  # Directory containing Dockerfile
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama_server  # Persists model registry between restarts
    environment:
      - OLLAMA_DEBUG=1  # Optional debug logging
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    mem_limit: "2g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: "1g"

volumes:
  ollama_data:
